name: "Prettier Fix"
description: "A GitHub action to apply Prettier fixes"

inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "20"

runs:
  using: "composite"
  steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Init package.json if it doesn't exist
        run: |
          if [ ! -f package.json ]; then
            npm init -y
          fi

      - name: Install dependencies
        run: npm install

      - name: Run Prettier and fix
        run: npx prettier --write .

      - name: Add changes
        run: git add .

      - name: Check for diffs in .github/workflows/*.yml file - to be fixed manually
        run: |
          for file in .github/workflows/*.yml; do
            if git diff --staged "$file" | grep -q .; then
              echo "::warning file=$file::Changes detected in $file. Manual intervention required to avoid conflicts with Super-Linter."
              git diff --staged "$file"
            fi
          done    

      - name: Set branch name and create branch
        run: |
          TIMESTAMP=$(date +'%y%m%d%H%M%S')
          SHORT_HASH=$(git rev-parse --short HEAD)
          BRANCH_NAME="prettier/fix-${TIMESTAMP}-${SHORT_HASH}"
          git checkout -b $BRANCH_NAME
          echo "New branch created: $BRANCH_NAME"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          #git add .
          # Commit changes without including .github/workflows
          git reset .github/workflows/*.yml
          git commit -m "Prettier fixes applied automatically on $(date +"%Y-%m-%d %H:%M:%S")"
          # Push changes to new branch
          git push origin $BRANCH_NAME
