---
name: Prettier-fix

on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"

  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"

permissions:
  contents: write

jobs:
  prettier-fix:
    runs-on: ubuntu-latest
    # Limit the running time
    timeout-minutes: 10
    steps:
      - name: Invoke the Prettier fix
        # Use the latest commit in the main branch.
        uses: WorkOfStan/prettier-fix@main
        with:
          commit-changes: true
          #debug: true
          #node-version: "20"
